name: Publish to Maven Central

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push
        run: |
          echo "${{ github.event.release.tag_name }}"